### ISSUE TITLE
ABCD Identification qualifier keeps showing on record detail page

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#100]
ABCD Identification qualifier hasn't been delivered for five years or more, but keeps showing on all record detail pages as 'Not provided' (which is correct I guess). Can it be removed? We deliver DwC identificationQualifier now and when it is not provided it shouldn't be there.

![image](https://user-images.githubusercontent.com/4694550/80929417-2d9a2b80-8def-11ea-9ff8-00ec946558ab.png)

**Comment by nickdos** [comment]
I think this is coming from the Collectory as a default value maybe? The data is in Cassandra, as can be seen from the "Original versus Processed" button. 

I'd rather fix this via the data than put in a hack to ignore it in the UI...

**Comment by nielsklazenga** [comment]
I can't find it anywhere in the Collectory. The weird thing is that it consistently shows up as 'Not provided'. It will probably be gone with the new pipeline, do you reckon?

**Comment by nickdos** [comment]
Yes, will be gone from pipeline, most likely. 

I'd guess there is some special case in biocache-store that is adding that processed attribute. I agree it doesn't look like Collectory is involved.

Will keep this open but might not prioritise for now.

**Comment by nickdos** [comment]
There is a config var to exclude fields from record page - so a quick fix is to add the DwC fields to `wc.exclude` in ansible.

**Comment by nielsklazenga** [comment]
Sounds good as a temporary fix. I take it it doesn't matter that this is not a Darwin Core field?

**Comment by nickdos** [comment]
Its any field on record page - tested on local version and it works. Ansible has been updated.
