### ISSUE TITLE
Add image icon to results list when record has images 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#114]
Requested by HISCOM and passed on by @nielsklazenga (low priority enhancement).

Show an image icon in the "records" tab on list view, for records that have associated images.

**Comment by nickdos** [comment]
![image](https://user-images.githubusercontent.com/532845/93740596-2b196080-fc2e-11ea-83d6-9e44e57ba316.png)

**Comment by nielsklazenga** [comment]
Thanks @nickdos , that looks very inoffensive. I can live with that.

**Comment by nickdos** [comment]
Needs code review & testing.

**Comment by nielsklazenga** [comment]
I can have a go at the code review, if it can wait two weeks. @acvaughan can do the testing.

**Comment by nickdos** [comment]
No rush, as we just had a release - leave to post TDWG ✅

**Comment by nickdos** [comment]
Hi @nielsklazenga , could you please review the code change ([link](https://github.com/AtlasOfLivingAustralia/avh-hub/commit/5321e921518e379e4c776b19ae087dee551a1e4a)) and check the functionality on test site (link above) is OK? Thnka

**Comment by nielsklazenga** [comment]
Done. Alison will have another look at https://avh-test.ala.org.au this afternoon.
