### ISSUE TITLE
Pittosporum undulatum searching matched_name_children

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#12]
From Alison Vaughan:

"I can successfully do a search for *Pittosporum undulatum* in the 'simple' search (788 records), but if I try from the Advanced search, I get the following message:
 `No Records found for matched_name_children:"pittosporum undulatum"`,
even though there are 784 records in the results of the simple search that have a provided taxon name of 'Pittosporum undulatum Vent.'."

Im not clear on why this is searching the matched_name_children field.
This is reproduceable in the new (grails) version of [ala-hub](https://github.com/AtlasOfLivingAustralia/ala-hub), so i presume the problem is with the new hub as well.

**Comment by acvaughan** [comment]
This appears to be working now.
