### ISSUE TITLE
Add data quality filter functionality to AVH

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#120]
DQ filters were added to ALA Biocache in early 2021, see screenshot:

![image](https://user-images.githubusercontent.com/532845/127791377-11931848-a0a0-4fcb-bbe2-8516d9e502ad.png)

For AVH, the suggestion (from NK) is to have a dedicated "AVH" data profile, that HISCOM will advise on. The other change compared to ALA would be to have the DQ filters disabled by default (so opt-in, not opt-out like ALA) and for the filters to be hidden by default too. Similar to this:

![image](https://user-images.githubusercontent.com/532845/127791510-becbc04f-e4c4-439d-99a2-9a051d09bec8.png)

**Comment by nickdos** [comment]
First version now up on test - https://avh-test.ala.org.au/occurrences/search?taxa=acacia+dealbata

PR: https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/473

**Comment by hxuanyu** [comment]
The
- View excluded records
- Learn More 
don't work. 

Learn More is a config issue. The `data_quality_learnmore_link` is not defined in `avh-test`

![1](https://user-images.githubusercontent.com/6880129/131269248-facf7707-655b-402c-9501-fd9a13fa69df.jpg)

**Comment by hxuanyu** [comment]
View excluded records link sometimes is wrong.
It's also an issue on prod

![3](https://user-images.githubusercontent.com/6880129/131269784-e401850d-7759-4a27-9dad-a496716d5a6c.jpg)
![2](https://user-images.githubusercontent.com/6880129/131269823-fe2d4341-79c5-4b55-aa93-b376fb35e2a9.jpg)

**Comment by hxuanyu** [comment]
the DQ category detail launched from the left side panel is not complete

![4](https://user-images.githubusercontent.com/6880129/131272359-fa98aa63-9bb8-4294-9917-0644f560e0d1.jpg)

**Comment by alexhuang091** [comment]
Hi @javier-molina, all issues fixed. Could please re-test it. Thanks

**Comment by javier-molina** [comment]
I'm on it after my two day exile.

**Comment by javier-molina** [comment]
Works for me.

**Comment by nielsklazenga** [comment]
I have one more minor niggle: 

![image](https://user-images.githubusercontent.com/4694550/132295806-175a2d52-6b46-4443-affe-0aa35e4aafef.png)

The number of records excluded is not a link, so should not look like a link. Also, I thought we were avoiding italics. Bold (but not green) would be better.

**Comment by nielsklazenga** [comment]
Sorry, accident.

**Comment by nickdos** [comment]
I agree @nielsklazenga and thought the same thing when i first saw it. But I had already argued for like a dozen changes before this, so decided to pick my battles and let it slip.

I think it should be bold text but NOT italics or coloured text.  Its got a CSS class so is a one-line change. Will try now.

**Comment by nickdos** [comment]
Deployed - try it again pls @nielsklazenga

**Comment by nielsklazenga** [comment]
@nickdos that number looks good now.
