### ISSUE TITLE
Advanced search - states & territories values are all jumbled together

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#124]
Since moving to Pipelines, all the possible states, territories and provinces are now included and the list is over 100 lines long, sorted alphabetically. The AU and NZ states are scattered throughout the list and are hard to find.

![image](https://user-images.githubusercontent.com/532845/132278177-3dcf99ed-dfdf-4531-9807-d63f0962e31e.png)

- [ ] Fix is to include states in the order of: AU, NZ and all others

**Comment by nickdos** [comment]
Fix now shows:

![image](https://user-images.githubusercontent.com/532845/132278736-993e68b9-e9d2-477e-a236-0dce6c8a5ce8.png)

**Comment by nickdos** [comment]
Deployed to test. 

@nielsklazenga could you test this pls?

**Comment by nielsklazenga** [comment]
Looking good.
