### ISSUE TITLE
Collector shows as "null" in search for some AVH records

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/avh-hub#134]
Reported in https://support.ehelp.edu.au/a/tickets/149559

Example search: https://avh.ala.org.au/occurrences/search?q=collector_text%3Akerrigan&qualityProfile=ALA&qc=data_hub_uid%3Adh9&fq=collection_uid%3A%22co25%22&offset=140&max=20

Screenshot shows results from the above example.

Records appear correctly if you open them individually - it's just the display of the collector field in search results that appears incorrect.

![image](https://user-images.githubusercontent.com/57081387/172974578-ca5b09cd-7657-4ff6-b87a-5da441789741.png)

**Comment by nickdos** [comment]
I had a quick look at this and it seems like either a biocache-service or pipelines issue. 

The JSON returned for the search results is missing the `collectors` attribute for some records and looking at an example record: https://biocache-ws.ala.org.au/ws/occurrence/d872b07f-2b09-4c7a-be50-a7dcead814cf - you can see there is no `recordedBy` data under the `processed` section.

**Comment by adam-collins** [comment]
Still an issue
