### ISSUE TITLE
Check obsolete fields in grouped facets

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/avh-hub#135]
There are a number of field mappings which have been changed. Those fields in facets may cause failure. All changes should be applied all hubs , e.g biocache-hub, ala-hub

After redeployment, the clients may need to clear related cookies.

Identified:
Remove min_elevation_d_rng

**Comment by qifeng-bai** [comment]
Linked to the same issue in Biocache-hub: https://github.com/AtlasOfLivingAustralia/ala-hub/issues/69

**Comment by adam-collins** [comment]
Field is removed. Closing.
