### ISSUE TITLE
Filtering by collector/s stops map interactivity

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/avh-hub#144]
Background: This relates to AVH only (not on ALA Biocache) and using the map tab to view records. 

Normally, clicking on a map point will load further info about that record.
However, filtering by `collector` using the UI facets makes the points on the map become unresponsive – when a point is clicked, a loading spinner symbol appears briefly then disappears in under one second.

See example:
https://avh.ala.org.au/occurrences/search?q=collector_text%3A%22mitchell%2C%20a.%22&disableAllQualityFilters=true&qualityProfile=ALA&qc=data_hub_uid%3Adh9&fq=collector%3A%22Mitchell%2C+A.A.%22#tab_mapView

This seems to be happening when either a single collector or multiple collectors are selected.

- Map works normally when an additional facet is added - for example, Country, Year, Record Type and Collection have all worked to restore the map functionality in testing
- It also seems to work fine using the URL, rather than the UI facets (see example: https://avh.ala.org.au/occurrences/search?q=collector_text%3A%22mitchell%2C+a.%22&disableAllQualityFilters=true&qualityProfile=ALA&qc=data_hub_uid%3Adh9#tab_mapView)

Raised by user, ticket https://support.ehelp.edu.au/a/tickets/181946

**Comment by adam-collins** [comment]
This is a biocache-service issue. Addressed in commit https://github.com/AtlasOfLivingAustralia/biocache-service/commit/0b8420913cbdcb67fe99977a1e93128961116575

**Comment by kylie-m** [comment]
This is working for me now using: 
https://avh-test.ala.org.au/occurrences/search?q=collector_text%3A%22mitchell%2C%20a.%22&disableAllQualityFilters=true&qualityProfile=ALA&qc=data_hub_uid%3Adh9&fq=collector%3A%22Mitchell%2C+A.A.%22#tab_mapView
