### ISSUE TITLE
ALA Legacy Format download is producing incomplete CSV

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/avh-hub#147]
On AVH, the ALA Legacy Format download option is producing CSV files with only 3 columns (see screenshot below)

![Screenshot 2024-01-11 at 3 24 12 pm](https://github.com/AtlasOfLivingAustralia/avh-hub/assets/90439797/faa56a7d-2df8-4698-bd7a-6d0cb49b96d1)

A correct CSV should have many columns.

Other notes for comparison and troubleshooting:
- On AVH, the Darwin Core download format is correct.
- On ALA BioCache, both Darwin Core and Legacy formats are correct.

- Raised by user: https://support.ehelp.edu.au/a/tickets/192632

**Comment by adam-collins** [comment]
Fixed. Please test.

**Comment by kylie-m** [comment]
Download is working correctly now  - thanks Adam!
