### ISSUE TITLE
NZVH Project: Organize harvest of NZ data for NZVH

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/avh-hub#15]
Setup harvest of NZ data into AVH...

Need to talk to Niels... If served as DwC (likely)... should come to ALA directly but he should get a copy...

**Comment by m-hope** [comment]
Manual harvest has been successfully completed from NZ Landcare Research's IPT website.

Need to automate the process.

**Comment by ansell** [comment]
Automated jenkins job created to pull the entire Darwin Core Archive from the IPT server each week and load it.
