### ISSUE TITLE
advanced search, states selection no longer puts AU and NZ states at the top

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/avh-hub#150]
This is different from the current biocache-hub approach. No need to change it, just needs fixing.

**Comment by timhicks-ala** [comment]
Raised in https://support.ehelp.edu.au/a/tickets/195504

**Comment by adam-collins** [comment]
Prod required a cache refresh. 
Test required config update.

**Comment by adam-collins** [comment]
biocache-hub commit https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/73c0205e683b8db64c7c55ccc8691861fc060b65

**Comment by adam-collins** [comment]
Short term solution is to fix config or clear cache.

Long term solution in the linked commits prevents caching of invalid states list.
