### ISSUE TITLE
Facet on subclass

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#2]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=286
_date:_ Sun Nov 10 19:18:51 2013
_author:_ moyesyside

---

Requested by HISCOM/CHAH

"This is not just to be able to filter for mosses – we won't be able to
do that anyway as long as there is no moss classification in ALA.
Liverworts, hornworts, ferns, angiosperms etc. are also all subclasses,
so subclass is one of the most important ranks in AVH. The facet is
needed to filter on each of these groups, or on combinations of these
groups, for example vascular plants, bryophytes and gymnosperms."

**Comment by m-hope** [comment]
As advised by the HISCOM meeting at Melbourne (Oct 2017), the taxonomy for Australian vascular plants has been changed to reflect the international hierarchy conventions and subclasses are no longer as important.  Therefore this issue is no longer needed.
