### ISSUE TITLE
Quick search doesn't return records for subordinate taxa

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#27]
We had a query from a user who was looking for records of Archidendron in AVH and found different numbers of records yesterday and today. We couldn't explain that, but when looking into the matter further at some point Alison and I started to get different results as well.

When you type 'Archidendron' in the Quick search box, it gets matched to an LSID and you get 131 records:

http://avh.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aapni.taxon%3A178658

On the other hand, when you type 'fq=genus:Archidendron' in the URL (or use the 'Genus' facet), you get 1786 records:

http://avh.ala.org.au/occurrences/search?q=*:*&fq=genus:Archidendron

When using the Quick search, you only get records that have only be identified to genus, or that have names that could only be matched to a genus name, while a query on genus will also return records of subordinate taxa. I think the latter is what people expect to have returned to them when doing a Quick search as well.

I don't know if it has always been like this, or has broken recently, but like to think that if it had always been like this I would have discovered it earlier.

BTW. I checked the development site as well.

**Comment by nickdos** [comment]
Looks OK on avh-test now:

http://avh-test.ala.org.au/occurrences/search?taxa=Archidendron
and 
http://avh-test.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2900791

**Comment by m-hope** [comment]
Confirm that quick search, taxon search, and genus search now all return same results
