### ISSUE TITLE
Facet on determination uncertainty

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#3]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=287
_date:_ Sun Nov 10 19:21:10 2013
_author:_ moyesyside

---

Requested by HISCOM/CHAH

The current 'Determination qualifier' facet is really about issues with
the provided names – I know we suggested the name, but it looked quite
different then – so its name should be changed. It is important for AVH
users to be able to discard uncertain determinations. As the Darwin Core
identificationQualifier is a free text field it is probably not all that
useful to have all values as facet items. Also, the rank to which the
qualifier applies is much more important than what (HISPID) qualifier is
used. We probably will want HISCOM to discuss how this facet should be
implemented, but it would be good to have an indication of what can be
done. A simple determination qualifier/no qualifier facet would already
be good, but if we can decompose it by rank would be great.

**Comment by acvaughan** [comment]
identificationQualifier has been added to AVH (at least in dev), but it would be great to add an option to 'Exclude all records with qualifiers':
The thing that most people will want to do with records that have identification qualifiers is exclude them from the results, as they are uncertain identifications. If the new interface is anything like the old one, people will only be able to exclude up to 15 facets; AVH has got more than 17,000 different identification qualifiers. A more useful facet would be one that separates records with an identification qualifier from records without.
 
Maybe that is something for later. For now, would it be possible to get an 'exclude uncertain identifications' check box to the advanced search for that adds -raw_identification_qualifier:[* TO *] to the query string?

**Comment by nielsklazenga** [comment]
Thanks @adam-collins! I had already added an 'Exclude uncertain identifications' option to the 'AVH' Data Quality Profile, but it will be great to have the identification qualifier among the filter options as well.

**Comment by adam-collins** [comment]
Named `Raw identification qualifier`
