### ISSUE TITLE
Enhancements to download records (csv)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#30]
Feedback from Frank Z:

> I downloaded more data and it took me a moment to find it: the field is in column AO and called 'record _ number'. Before download the field is called 'Collecting Number' so that is a little confusing. Also is it possible for the field to appear after column AD which is 'Collector' as these two data elements should be together?

which boils down to:
* provide custom header name for `recordNumber` as `Collecting Number`
* change order of fields so `recordNumber` appears after `collector`

**Comment by acvaughan** [comment]
I agree that both are sensible suggestions (especially the second one). We (both the zoological and botanical communities) had requested that the column headers are consistent with Darwin Core terms, but I can't find an issue for this in GitHub.

**Comment by nielsklazenga** [comment]
The column headings in the downloads are not customisable for AVH, but are the same throughout the BioCache, right? If that is the case, I agree with the wish of FCIG that the column headers in the downloads correspond as much as possible to the Darwin Core terms (which Alison just confirmed while I am writing this). So, _recordNumber_ should stay _recordNumber_ and _collector_ should be changed to _recorder_.

**Comment by nielsklazenga** [comment]
Just looking at the [Download fields](https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0) document in Google Docs, and notice that _recordNumber_ is not in that list. Other than that, the column headers pretty closely match Darwin Core. There are just a few that do not: _collector_ that was already mentioned, _state_ that could be changed (and matched) to _stateProvince_ and _latitude_ and _longitude_ that could be changed to _decimalLatitude_ and _decimalLongitude_ respectively. I am not at all fussed by these minor discrepancies, by the way.

**Comment by nickdos** [comment]
Yes, `recordNumber` is being used as `collecting number` here, so the AVH would be requiring a custom header as ALA would want to stay with `recordNumber`. But as Niels points out "collector" would be [`recordedBy`](http://rs.tdwg.org/dwc/terms/#recordedBy) if we went with DwC terms and `recordNumber` would stay as `recordNumber`.

**Comment by nielsklazenga** [comment]
AVH wants to stay with `recordNumber` as well.
