### ISSUE TITLE
Another name matching error

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#32]
A [search for Eclipta alatocarpa](http://avh.ala.org.au/occurrences/search?taxa=Eclipta+alatocarpa#tab_recordsView) shows a record for New South Wales. When you open that record, [CANB 334476](http://avh.ala.org.au/occurrences/015f3cd6-440b-4750-a4b9-ab007d0893b1), it turns out both the provided and processed name for the specimen is _Sigesbeckia microcephala_.

This record is in the AVH cache as CANB 334476.1 and Eclipta alatocarpa. Also, this record was last updated in the AVH cache on 2 March 2014, while it was last loaded in ALA on 20 July 2012, which is the date we first started to deliver from the AVH cache. CANB at that time was changing over its database so the CANB data was old (Nov. 2011). CANB first started delivering data again in September or October 2013 and then it had changed all its catalogue numbers. The new CANB (and CBG and CNS) catalogue numbers all have '.1' etc. suffixes, which the old ones didn't. Is it possible that an old record is hanging around, preventing the new record from displaying? Somehow the index did pick up the new record.

**Comment by m-hope** [comment]
This now seems to be resolved... the only AVH record for CANB334476 is http://avh.ala.org.au/occurrences/015f3cd6-440b-4750-a4b9-ab007d0893b1. And this record now has a supplied name of: "Eclipta alatocarpa Melville", with a load date of 2016-03-01.
