### ISSUE TITLE
Link to ALA image viewer

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#33]
Miles uploaded the first few images that can be linked to AVH occurrence records last week, see for example http://avh.ala.org.au/occurrences/929e2d86-17a3-4947-aad0-5d8bf7dc7a7e. Could the link under the thumbnail be changed so that it opens the image in the ALA imange viewer, as is already happening in the Biocache?

**Comment by djtfmartin** [comment]
This should just be a config change & a restart.

**Comment by nielsklazenga** [comment]
Thanks Nick, it's working.
http://avh.ala.org.au/occurrences/929e2d86-17a3-4947-aad0-5d8bf7dc7a7e
