### ISSUE TITLE
Missing records

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#34]
The following query: http://avh.ala.org.au/occurrences/search?taxa=Solidago%20chilensis#tab_recordsView, gives three records, all of which when you click on them to go to the occurrence detail page give an error message, saying that the record doesn't exist.

This is different from the earlier situation with CANB records where records would show up in the index that shouldn't be there any more, as in the current case the index is correct.

I have updated the three records in the MEL collections database, so they will come through again with the next AVH harvest, so we can see if that "fixes" the problem.

**Comment by djtfmartin** [comment]
This is a result of the outages over the weekend. We are still working on fixing this service.

**Comment by nielsklazenga** [comment]
Yes, thought so. it is just that I get the phone call and must be seen to be doing something.

**Comment by djtfmartin** [comment]
No problem. All fixed now.
