### ISSUE TITLE
Go to Records view when paging through records

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#35]
Currently, when you try to go to the next page of records in an AVH search result, you go to the Map view instead.

**Comment by ben3000** [comment]
This appears to be fixed in development versions, and should be fixed by releasing a new version from master.

**Comment by nickdos** [comment]
Yes, seems OK in avh-test now...

http://avh-test.ala.org.au/occurrences/search?taxa=&q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2900791

**Comment by nielsklazenga** [comment]
Excellent
