### ISSUE TITLE
full resolution records are not available with AVH_CLUB access

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/avh-hub#36]
can't see the unsensitied location even with AVH_CLUB role - e.g. http://avh.ala.org.au/occurrences/search?taxa=Thelymitra+fragrans#tab_recordsView

**Comment by adam-collins** [comment]
Moved to https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/558
