### ISSUE TITLE
Ordering of LGA and IBRA region facets

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#38]
The ordering by descending number of returned records of the IBRA region and, especially, LGA facets makes it very hard to find an individual facet. Is it possible to order them alphabetically instead, as has been done for the some of the taxonomic facets? If so, better wait for discussion at HISCOM, as there are things to say for both ways of ordering.

The drop-downs in the Advanced Search field should of course always be in alphabetical order.

**Comment by nickdos** [comment]
Ordering of facets is via the `index|count` value for `sort` in the file:

https://github.com/AtlasOfLivingAustralia/avh-hub/blob/master/grouped_facets.json

As comment above says, there are advantages to having sort for either option. So discussing at HISCOM is a good idea.

**Comment by m-hope** [comment]
General consensus is that all regional based fields in both Advanced Search and Facets should be sorted alphabetically... includes: LGA, IBRA, NZ provinces, NZ districts and NZ regions.

**Comment by m-hope** [comment]
All the area based drop downs in the Advanced Search page are now listed alphabetically.
In the results section all facets are listed by count, but by clicking on the 'choose more' button under each facet, the user has the ability to select the ordering by clicking on the column heading.   This has been discussed at HISCOM as an acceptable compromise for the display of area based fields.
