### ISSUE TITLE
advanced search with multiple criteria

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#39]
> On 7 Oct 2015, at 4:30 pm, Murray Fagg <murray@anbg.gov.au> wrote:
Nick
>
 Following on from our phone conversation about using local government and IBRA restrictions on plant searches.
>
What I was trying to do was find out the records for a genus, in this case Melaleuca for an IBRA region or a local government region.
>
If I put < Melaleuca > in the Taxon field and < Ceduna > in the local government field it produces records for all the herbarium specimens ID'd to the genus only for the whole of Australia (not just Ceduna).
>
The same for IBRA.
>
I presume I need a wild-card after the genus name in the taxon field, but couldn't figure what it is, I tried '%' and '*' and '_'  but none worked.
A web Google query on "wild-card" symbol for ALA didn't get me anywhere.
>
Murray

**Comment by nielsklazenga** [comment]
=#39

**Comment by ben3000** [comment]
This clearly works for an IBRA search, e.g. text:banksia and IBRA:"Jarrah Forest", but still doesn't work for LGAs.
