### ISSUE TITLE
Additional spatial query options

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#4]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=288
*date:* Sun Nov 10 19:21:56 2013
*author:* moyesyside
 ---

Requested by HISCOM/CHAH

"Having to create a shapefile before you can do a spatial query is a bit
rough on the average AVH user. It is also a bit misleading, as only the
first polygon in the shapefile is used. I know it was a demand from CHAH
to have the shapefile query. The suggestion to add bounding box, WKT and
KML options is based on the assumption that the actual query that takes
place is already a WKT query and that the conversion from the other
formats takes place in the UI."

**Comment by nickdos** [comment]
WKT and draw tool now in search options
