### ISSUE TITLE
Change some facet titles

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#47]
Could the following facet titles in the AVH hub be changed?

| From | To |
| --- | --- |
| Cl927 | States (including coastal waters) |
| Cl958 | Commonwealth Electoral Boundaries |
| Cl1049 | IBRA 7 Subregions |
| Cl916 | NRM Regions |
| Ecoregions | IRMNG Habitat |

Also, could all these facets be turned off by default? It would also be good if the IBRA subregions could be directly below the IBRA regions.

**Comment by nielsklazenga** [comment]
I think I just found out how to do it: https://github.com/AtlasOfLivingAustralia/avh-hub/blob/master/grails-app/i18n/messages.properties.

May I?

**Comment by nickdos** [comment]
Closing as all facets have labels in current test version.
