### ISSUE TITLE
Remove IBRA 6 regions facet

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#49]
There are now facets for IBRA 6 and 7 regions and IBRA 7 subregions. Bit much, so can the IBRA 6 facet be removed?

I think this may have come up in HISCOM.

**Comment by nickdos** [comment]
Removed from config https://github.com/AtlasOfLivingAustralia/ala-install/commit/fe96bd3ca7f70a0ee873b6331b7fa335b478b57e
