### ISSUE TITLE
 Ability to download any field and to choose the fields that are downloaded

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#5]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=289
_date:_ Sun Nov 10 19:23:18 2013
_author:_ moyesyside

---

Requested by HISCOM/CHAH

"this is what AVH users have asked for more frequently than anything else."

**Comment by m-hope** [comment]
This functionality (the new ALA download capability) has been incorporated in the release of the Australasian Virtual Herbarium. This now gives users the ability to select any field to download (including all available fields).
