### ISSUE TITLE
Include infraspecific taxa in the Species Checklist download

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/avh-hub#50]
_From @acvaughan on March 13, 2015 1:14_

The Species Checklist only lists the taxa in a given area to species level, but users generally want to know what species, subspecies, varieties and forms are in the area. 

HIGH PRIORITY

_Copied from original issue: AtlasOfLivingAustralia/ala-downloads#12_

**Comment by adam-collins** [comment]
The request from the downloads-plugin includes `facet=species_guid`. Maybe make it configurable and use `taxonConceptID` for avh-hub? Make it a general option for selection in the downloads plugin? Need to confirm.

**Comment by nielsklazenga** [comment]
It is actually better to leave this a **species** checklist, as adding infraspecific taxa to the checklist will cause a lot of extra problems, as people might not always identify down to the level of subspecies or variety and one taxonomy might recognise a subspecies or variety and another one not.

**Comment by adam-collins** [comment]
In light of this comment, no changes required.
