### ISSUE TITLE
Lord Howe Island is called Norfolk Island on map

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#51]
Oops...

![avh screen grab](https://cloud.githubusercontent.com/assets/4694550/13202420/434e93ae-d8ee-11e5-946f-d2ae73677d7e.jpg)

Screenshot courtesy of John Huisman.

**Comment by nickdos** [comment]
I've reported this to CartoDB via their issue system. https://github.com/CartoDB/CartoDB-basemaps/issues/53
