### ISSUE TITLE
Add Collecting Number to popup when map data points clicked.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/avh-hub#54]
Adding the Collecting Number (stored as record_number field) to the popup tag that is displayed when a data point on the map is clicked would significantly increase productivity to AVH users as this is a critical piece of information to identify duplicate records.  Currently users have to open each suspect record in order to gather that information.  Note: this is probably only relevant for Herbaria staff so only needs to be implemented on AVH.

**Comment by nickdos** [comment]
Added to biocache-hubs - pulling this code out just for AVH was going to be really messy so added it to all hubs for now. https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/6d90c7b74605b7f168f6257b663563ca203b3f63

**Comment by nielsklazenga** [comment]
Good decision!
