### ISSUE TITLE
API docs for annotation web services

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#55]
I have been playing around with the annotation web services and found out that some of the documented services I couldn't get to work and others didn't work because the documentation is incomplete. Suggestions for improved documentation are in [this Google Doc](https://docs.google.com/document/d/1RLui8rq4aIfJweOnmL-8BARPoelagItZcJj2e6TaIDE).

**Comment by adam-collins** [comment]
use https://docs.ala.org.au/ today
