### ISSUE TITLE
Indexing of establishmentMeans

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#56]
establishmentMeans is a very important field for the botanical community. People might want to exclude records of cultivated plants from their search research altogether and, when mapping, we would like to use different symbols for the different establishment means values. We might even want to be able to 'Colour by' establishmentMeans (the current 'Colour by' establishment means in the AVH hub does not or not only use the establishmentMeans field and has a lot of deprecated values (that is probably an issue in itself)). For the mapping with different symbols we need to know the value of establishmentMeans for every record (for which it has been recorded), so we need to be able to download the field, also when using the web services.

establishmentMeans is both indexed and stored in the index, yet we can search on it and we can have a facet on it, but we cannot download it. The reason for this is that establishmentMeans is indexed as a multi-value field. I can't think of a reason why the establishmentMeans field would need to be multi-valued, as it is a single-value term in Darwin Core, you can't deliver multi-value fields in CSV unless you concatenate the values, and the establishmentMeans field is not processed in ALA. Even so, I would like to be able to download multi-value fields, especially since there are other multi-value fields people may wish to download, for example reproductiveStatus.

**Comment by adam-collins** [comment]
Done
