### ISSUE TITLE
Add multimedia facet 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#58]
Now that there are images in the AVH data set, we need to add the `multimedia` back into the `grouped_facets_avh.json` file. Not sure which section it should go... Any suggestions?

**Comment by nielsklazenga** [comment]
Put it under **Occurrence**. That's where it is in Darwin Core: [`associatedMedia`](http://rs.tdwg.org/dwc/terms/associatedMedia).

**Comment by nickdos** [comment]
Its under `record` right now (not sure who did this) - `occurrence` is already very big, so evens out the categories... re-open if it needs to go under `occurrence`

**Comment by nielsklazenga** [comment]
It does need to go to Occurrence, but it is in under Record in the system you set up with Alison two years ago, so leave it there for now. I suggested a whole swag of changes to the facets (https://github.com/hiscom/avh-testing/issues/1), including this one, last year, which has been ignored by HISCOM. We'll do them all together once a decision have been made.
