### ISSUE TITLE
Facet grouping: Conservation status

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#60]
The 'Conservation status' facet should be moved from the **Occurrence** group where it is now to the **Taxon** group. Also, 'Conservation status' is really 'State conservation status', so we should call it that and we should add the 'Country conservation' facet, which we do not have yet.

**Comment by nickdos** [comment]
Changed here: https://github.com/AtlasOfLivingAustralia/ala-install/commit/d22b55882e143fa8b006849a925ed85eef4d95d6
