### ISSUE TITLE
Genus searches are failing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#61]
http://avh.ala.org.au/occurrences/search?taxa=Sistotrema#mapView 

should resolve to:

http://avh.ala.org.au/occurrences/search?q=genus%3A%22Sistotrema%22

but doesn't. `Acacia` also fails - looks like issue with BIE lookup

**Comment by ben3000** [comment]
These queries return the same number of results now, does that mean it is fixed, or are you pointing to a different problem?

**Comment by nickdos** [comment]
Yes - BIE issue now fixed.
