### ISSUE TITLE
Flag an issue appears to do nothing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#62]
The annotation actually gets submitted but to the user it seems that the submit button is broken, as there is no confirmation or any other feedback.

**Comment by ben3000** [comment]
See https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/89d0596cdc8a2b29f27c55f0f7bcbdcd75a31b20 for a partial fix.

**Comment by ben3000** [comment]
It testing code for this, I notice there's a bit of a race condition in the processing of annotations. I was able to delete an annotation before a verification finished being added, resulting in a partial annotation being displayed on the page. I was able to clean it up, thankfully.

**Comment by m-hope** [comment]
This needs to be a more general check of the "Flag an Issue" function, including:
- Users can submit annotations successfully
- Admins can check/verify/refute a user annotation (old issue #43)
- Collection admins who have registered for Annotation alerts actually get the notification

**Comment by adam-collins** [comment]
Closing. Reopen or create new issue if it happens again.
