### ISSUE TITLE
Provided scientific name has disappeared from downloads

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#66]
It seems that the verbatim scientific name is only still available in the 'ALA Legacy Format'. Any chance we can get this back in the 'Customised Download'?

At the moment it is rather confusing for people who are not aware of what is going on during the aggregation, as what is called 'Scientific Name' in the ALA legacy format is is the scientific name that was provided with the record, while 'scientificName' in the new downloads is the interpreted scientific name (this was 'Matched Scientific Name' previously). I had a delegation from DELWP here yesterday, who asked me about it (that's the only reason I was checking), as they couldn't find the names they had delivered back in the downloads, so it is not just taxonomists who are interested in it.

I also noticed that the specificEpithet column is in the 'Full Darwin Core' download twice and the values in one of these columns (the other one is empty) are not specific epithets, but species names.

**Comment by nickdos** [comment]
Might leave this, for testing with new download plugin, that provides option for full DWC and customised downloads...

**Comment by adam-collins** [comment]
Fixed recently
