### ISSUE TITLE
Can't search by catalogue number or batch catalogue numbers

### ISSUE THREAD

**Issue by ryonen** [AtlasOfLivingAustralia/avh-hub#67]
Searching by catalogue number in the 'Advanced search' and 'Catalogue number search' tabs in ALA & AVH fails to return any records regardless of the institution (e.g. http://biocache.ala.org.au/occurrences/search?q=catalogue_number%3A%22CANB+819747.1%22).

Batch catalogue number searches also fail to return any records.

Also logged at https://github.com/AtlasOfLivingAustralia/maintenance/issues/62

**Comment by nickdos** [comment]
Just tested this with latest code and both advanced and batch options returned the expected results when pasting `CANB 819747.1`.

**Comment by nickdos** [comment]
http://avh-test.ala.org.au/occurrences/search?q=qid:1495779678071

looks ok to me

**Comment by nielsklazenga** [comment]
To me too.
