### ISSUE TITLE
Advanced search with collector field fails

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#68]
Using the search terms "Thiele, K.R." in collector and "3254" in collecting number returns 0 results:

http://avh.ala.org.au/occurrences/search?q=record_number%3A3254+collector_text%3A%22Thiele%2C+K.R.%22

but this URL shows 1 result:

http://avh.ala.org.au/occurrences/search?q=record_number:3254%20collectors:%22Thiele,%20K.R.%22

Difference is the field "collectors_text" vs "collectors". "collectors_text" should match the same way that "collectors" does.

**Comment by nickdos** [comment]
This now returns 1 result with latest code (local). Needs checking once deployed to avh-test.

**Comment by nickdos** [comment]
http://avh-test.ala.org.au/occurrences/search?q=record_number%3A3254+collector_text%3A%22Thiele%2C+K.R.%22

**Comment by nielsklazenga** [comment]
Great. Also works with 'Thiele, K.' in the search string.

**Comment by m-hope** [comment]
Resolved.
