### ISSUE TITLE
Updating to Grails-2.5.6 breaks compilation due to AvhAdvancedSearchParams.toString2

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/avh-hub#70]
The ``toString2`` method was introduced into ``AvhAdvancedSearchParams`` with an ``@Override`` tag in https://github.com/AtlasOfLivingAustralia/avh-hub/commit/6a61af2a254fa5aed6809ce9a00a3a21444ea5af

Grails-2.3 doesn't seem to identify that as an error, but updating to Grails-2.5.6 breaks complication, as there is no ``toString2`` method in the biocache-hubs copy of ``AdvancedSearchParams``. It is possible that the underlying Groovy version used by these two versions of Grails started to identify broken uses of ``@Override`` between those two versions.

**Comment by adam-collins** [comment]
Obsolete issue
