### ISSUE TITLE
Add matched name to results list

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#72]
AVH shows provided name in result but this can be confusing when a search uses a matched name (e.g. taxa search). Niels and Gill suggest displaying the matched name and show provided name after it.

http://avh.ala.org.au/occurrences/search?q=record_number%3A2439+collector_text%3ASankowsky

> Elattostachys bidwillii (Benth.) Radlk.

should be:

> Elattostachys xylocarpa | provided name: Elattostachys bidwillii (Benth.) Radlk.

**Comment by afuchs1** [comment]
This would be fantastic and avoid much confusion. Do we only need to display the provided name it is different?

**Comment by nickdos** [comment]
@afuchs1 - yes, only when different.

**Comment by nielsklazenga** [comment]
I didn't dare to ask, but that is even better.

**Comment by nielsklazenga** [comment]
Hi Nick,
We were going to do it the other way around.

Not:
> Elattostachys bidwillii (Benth.) Radlk. — matched name: Elattostachys xylocarpa

but:
> Elattostachys xylocarpa | provided name: Elattostachys bidwillii (Benth.) Radlk.

**Comment by nickdos** [comment]
I should've checked first and I can change it easily... but the reason I switched it around, was because I thought it was a **smaller** change so less likely to confuse people(?). AVH previously showed just the provided name, so adding matched name second is less likely to confuse? E.g. AVH still show provided name first (and only in many cases) but when different, the provided name is ALSO shown. If you get what I’m saying…

**Comment by nielsklazenga** [comment]
Yes, I do get what you are saying, but I think it was having the provided name in the search result and the matched name everywhere else that was confusing people. We'll discuss it at HISCOM next week. See what people think.

**Comment by nickdos** [comment]
We also need to discuss the advanced search - taxa search part... It uses the matched name but I have a feeling it used to search against provided name. Was thinking we might be able to add a toggle to choose which to use maybe - see https://github.com/AtlasOfLivingAustralia/avh-hub/issues/73

**Comment by nielsklazenga** [comment]
Yes, I saw that issue and it will be in my Powerpoint.

**Comment by nielsklazenga** [comment]
Still need to change the order of the names, so it is done consistently throughout the application (always the matched name first).

So:
> Elattostachys xylocarpa | provided name: Elattostachys bidwillii (Benth.) Radlk.

rather than:
> Elattostachys bidwillii (Benth.) Radlk. — matched name: Elattostachys xylocarpa

(which it is now).

**Comment by nickdos** [comment]
Thanks for reminder - slipped off my radar

**Comment by nielsklazenga** [comment]
Just me following up on what was discussed in the HISCOM meeting, which is where we had left this at.

**Comment by nickdos** [comment]
![image](https://user-images.githubusercontent.com/532845/37324453-98f5c31a-26dd-11e8-86ad-c2c6ad8e6e66.png)

**Comment by nielsklazenga** [comment]
Beautiful!
