### ISSUE TITLE
Issues with user stats

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#80]
Just dumping some emails from David Cantrill here:

> [2017-12-06]
>Hi Niels,
>
>We have been using the ALA data use stats provided to data custodians as part of our business case for an uplift in funding and the new herbarium bid.
>
>There appears to be an issue with 2016.  Data use dropped dramatically for us (and for others) but has returned to trend in 2017.  Looking at more detail in the monthly breakdown there appears to be an issue with the data provided for August 2016 with virtually no download events.  I cannot really tell if it has spilled over into July and September 2016.  Can you please ask someone at the ALA to check this and to provide the actual usage for this month.  Even better if they can just update the spreadsheet on the download stats pages as the consultants building the business case are using this as a data source.
>
>From my perspective this is fairly urgent as we need to put something to the board next week.

> [2017-11-27] 
> Hi Niels
>
> I wonder if you could find out for me how the usage stats are working (or not).  Users are asked to supply a reason and 12 categories are listed.  However, in the usage stats several redundant categories are still being reported so there appears to be some glitch that allows a user downloading information to “bypass the categories”  perhaps via an old cache.  Currently there are 12 categories in the required field pull down menu but in the data supplied back to us there are 14 categories including two  that do not appear to be an option  from the pull down required field menu e.g. unclassified, other scientific research.  Can you please raise this with the ALA as an issue that needs resolving.

**Comment by adam-collins** [comment]
Not sure if still relevant.
