### ISSUE TITLE
Prevent people from selecting impossible combinations of facets

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#81]
An issue was reported where people try to filter on a combination of facets with a value and the facet for where the field is missing and get unexpected results.

http://avh.ala.org.au/occurrences/search?q=country%3AAustralia+collector_text%3ABanks&fq=kingdom%3A%22Plantae%22&qc=data_hub_uid:dh9&fq=(occurrence_decade_i%3A%221770%22%20OR%20occurrence_decade_i%3A%221790%22%20OR%20-occurrence_decade_i%3A*)#tab_mapView

![image](https://user-images.githubusercontent.com/4694550/35465766-82a9c36c-0352-11e8-9bf9-fc57f9412550.png)

It is not possible in SOLR to combine the '(blanks)' facet with other facets for the same field, but not all users know that. It would be good if users could be prevented from choosing impossible combinations of facets, _e.g._ by un-selecting all other facets when the '(blanks)' facet is ticked and un-selecting the '(blanks)' facet when any other facet is ticked.

**Comment by adam-collins** [comment]
It now works. It forms a valid query to get the expected result.
