### ISSUE TITLE
Update AVH skin with new logo and colours

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#82]
See new version http://data.rbg.vic.gov.au/avh/

Pending approval for new skin by chah/hiscom.

**Comment by nielsklazenga** [comment]
This is not the new skin. It was just a mock up to show how horrible it looks. There is supposed to be a new design made this year, which also will have to include a newly designed logo, as this logo is incredibly frumpy and might look good on a serviette or on the tiles of the CHAH executive bathroom, but doesn't work on the web.

**Comment by nickdos** [comment]
Ah OK. Will keep issue for when the eventual design is approved, we can propagate it to avh-hub.

**Comment by nickdos** [comment]
Closing this as it appears to not be hapenning soon. Easy enough to create new issue if it comes up again.
