### ISSUE TITLE
Use biocache-service autocomplete service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#83]
ATM AVH is using the default BIE autocomplete service but there is the option to use the biocache-service autocomplete service which will use names contained within the AVH occurrence record data. 

It might be worth trying this out and testing it,  to see if it provides more useful suggestions than the BIE (which can prompt with animal names sometimes).

**Comment by nickdos** [comment]
Related to AtlasOfLivingAustralia/biocache-hubs/issues/128

**Comment by adam-collins** [comment]
Configurable but no identified demand.
