### ISSUE TITLE
provide a hyperlink to the IBRA and IMCRA websites from the advanced search page.

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/avh-hub#86]
I have a minor suggestion to make AVH even more useful: provide a hyperlink to the IBRA and IMCRA websites from the advanced search page.
I rarely use IBRA regions in my botanical work so I don’t remember how they correlate with State ‘botanical’ regions. It would be helpful to me and no doubt to others in narrowing a search in AVH if there was a hyperlink to the IBRA website to work out which region was relevant. The same would presumably apply to IMCRA regions, which I have no occasion to use.

**Comment by nielsklazenga** [comment]
This information is in the [Help pages](http://avh.chah.org.au/index.php/help/data/#IBRA_7_regions). We are in theory able to link to relevant bookmarks in the Help pages, but such links are much more important with the facet fields on the Search Result page and on the Record Detail page, which cannot be customised. Therefore, we have decided to be consistent and not to have them in the Advanced Search either.
