### ISSUE TITLE
show Record Images tab in AVH occurrence search results by default

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/avh-hub#88]
At the moment, the Record Images tab is not shown in the initial set of search results. 

@elywallis reported that herbarium users are having to select the Multimedia:Images facet in order to get the Record Images tab to appear.

**Comment by ansell** [comment]
These are the relevant biocache-hubs issues which have both been marked as "fixed" with a configurable option to restore the behaviour users actually want, but it is possibly off by default for some reason:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/268

https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/267

**Comment by matthewandrews** [comment]
It appears to be working as intended for non-AVH searches, but searches via AVH still have this problem.  Presumably needs a change in AVH hub (or perhaps a change in defaults).

**Comment by elywallis** [comment]
Hi all, any chance this bug could be moved along the board? I'm visiting Queensland Herbarium next week (10 October) who originally requested this be fixed. It would be great to report back to them that it's done. Thanks

**Comment by djtfmartin** [comment]
Ive done this for AVH.

**Comment by djtfmartin** [comment]
and done for OZCAM too :)

**Comment by elywallis** [comment]
Thanks @djtfmartin much appreciated!
