### ISSUE TITLE
HISCOM: Provide image metadata fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#9]
From 2013 meeting minutes, actioned against @djtfmartin. HISCOM wants a list of image metadata fields that other data providers are using when importing data into the ALA.

**Comment by m-hope** [comment]
The following information has been provided to the HISCOM/MARC community via the HISCOM github repository (https://github.com/hiscom/business/issues/50).

"Currently there is no system enforced minimum requirements for image metadata (ie: you can still add an image with no metadata), however it is recommended that you at least include: license or rights information, photographer and rights holder (if different to photographer)."
